apiVersion: v1
kind: Service
metadata:
  name: __app__
spec:
  type: NodePort # ClusterIP
  ports:
  - protocol: TCP
    targetPort: 8080  # 애플리케이션(파드)을 노출하는 포트
    port: 8080      # 서비스를 노출하는 포트
  selector:       # 이 서비스가 적용될 파드 정보를 지정 (선택이나 권장 사항)
    app: __app__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __app__
  labels:
    app: __app__
spec:
  revisionHistoryLimit: 2
# hpa 할려면 replicas 있으면 안됨
  replicas: 1
  selector:
    matchLabels:
      app: __app__
  template:
    metadata:
      labels:
        app: __app__
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: __app__
        image: j11xn8h3.private-ncr.gov-ntruss.com/__app__
        command: ["java", "-Dspring.profiles.active=__namespace__","-jar","/portal.war"]
#        resources:
#          limits:
#            memory: 1Gi
#          requests:
##            cpu: 0.5
#            memory: 1Gi
# image 에 tag 없거나 latest 이면 imagePullPolicy default 가 Always
#        imagePullPolicy: Always
        volumeMounts:
        - name: prodnas1
          subPath: __namespace__/ideanas/
          mountPath: /ideanas/
        ports:
        - containerPort: 8080
# 컨테이너가 요청을 처리할 준비가 되었는지
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
# 컨테이너가 동작 중인지
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
      volumes:
      - name: prodnas1
        nfs:
          server: 169.254.170.76
          path: /n009457_prodnas1/
#        mountOptions:
#        - hard
#        - nolock
#        - nfsvers=3
#---
#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: __app__
#spec:
##  maxReplicas: 5
##  minReplicas: 2
#  maxReplicas: 1
#  minReplicas: 1
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: __app__
##  targetCPUUtilizationPercentage: 80
#  metrics:
##  - type: Resource
##    resource:
##      name: cpu
##      target:
##        type: Utilization
##        averageUtilization: 70
#  - type: Resource
#    resource:
#      name: memory
#      target:
#        type: Utilization
#        averageUtilization: 70
